#!/usr/bin/env python3
"""
AutoResearch Orchestrator — Karpathy Loop for SST-2 Optimization
=================================================================

Key design principles:
  1. SURGICAL EDITS — Code Agent only outputs the exact lines to change
     (old_snippet → new_snippet). Never rewrites the whole file.
     This eliminates context-decay truncation completely.

  2. SELF-CORRECTING AUDIT LOOP — When the Auditor rejects code, the
     rejection reason is immediately fed back to the Code Agent for
     retry. The agent must fix the specific issue, not repeat it.

  3. ReCAP PATTERN — program.md goal is re-injected into every LLM call
     to prevent plan drift in long-running research sessions.

  4. RATCHET — Git commits only on genuine accuracy improvement.
     Failed experiments are reverted via git reset --hard.

Workflow per iteration (PRAR):
  PERCEIVE  → read program.md + results.tsv
  REASON    → Lead Researcher proposes ONE hypothesis
  ACT       → Code Agent applies surgical edit
              → 2-second syntax check
              → Auditor approves/rejects (with retry feedback loop)
  REFLECT   → run training, parse accuracy, commit or revert
"""

import ast
import anthropic
import csv
import json
import os
import re
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# ── Constants ──────────────────────────────────────────────────────────────────
MODEL = "claude-opus-4-6"
RESULTS_FILE = "results.tsv"
TRAIN_FILE = "train.py"
PROGRAM_FILE = "program.md"
PREPARE_FILE = "prepare.py"
MAX_TRAIN_TIMEOUT_S = 370       # OS hard timeout (train.py self-stops at 300s)
PLATEAU_WINDOW = 5              # consecutive ran-experiments for plateau check
PLATEAU_THRESHOLD = 0.001       # <0.1% gain → plateau
MAX_CODE_RETRIES = 3            # max Code Agent retries per hypothesis

client = anthropic.Anthropic()


# ── File helpers ───────────────────────────────────────────────────────────────

def read_file(path: str) -> str:
    with open(path, "r") as f:
        return f.read()


def write_file(path: str, content: str) -> None:
    with open(path, "w") as f:
        f.write(content)


# ── Results TSV ────────────────────────────────────────────────────────────────

def read_results() -> list[dict]:
    p = Path(RESULTS_FILE)
    if not p.exists() or p.stat().st_size == 0:
        return []
    with open(RESULTS_FILE, newline="") as f:
        reader = csv.DictReader(f, delimiter="\t")
        return list(reader)


def append_result(
    iteration: int,
    hypothesis: str,
    accuracy: float,
    status: str,
    commit_hash: str,
    peak_memory_mb: float,
    notes: str,
) -> None:
    needs_header = (
        not Path(RESULTS_FILE).exists()
        or Path(RESULTS_FILE).stat().st_size == 0
    )
    with open(RESULTS_FILE, "a", newline="") as f:
        writer = csv.writer(f, delimiter="\t")
        if needs_header:
            writer.writerow(
                ["iteration", "hypothesis", "accuracy", "status",
                 "commit_hash", "peak_memory_mb", "notes"]
            )
        writer.writerow(
            [iteration, hypothesis[:80], f"{accuracy:.4f}", status,
             commit_hash, f"{peak_memory_mb:.1f}", notes[:120]]
        )


# ── Distiller: auto-update program.md with forbidden search paths ─────────────

def distill_beliefs(results: list[dict]) -> None:
    """
    Scan results for hypotheses that have been tried 3+ times and always failed
    (REVERTED). Extract the key variable being changed (e.g. N_LAYERS=3) and
    write/update an '## AUTO-DISTILLED FORBIDDEN CHANGES' block in program.md.
    Only updates if there are new forbidden patterns not already in the file.
    """
    ran = [r for r in results if r["status"] in ("REVERTED", "COMMITTED")]
    if len(ran) < 3:
        return

    # Count occurrences of each hypothesis keyword (first 40 chars as key)
    from collections import Counter
    hyp_counts: Counter = Counter()
    hyp_accuracies: dict[str, list[float]] = {}
    for r in ran:
        key = r["hypothesis"][:50].strip()
        hyp_counts[key] += 1
        hyp_accuracies.setdefault(key, []).append(float(r["accuracy"]))

    # Find hypotheses tried 3+ times that were never committed
    committed_hyps = {r["hypothesis"][:50].strip() for r in results if r["status"] == "COMMITTED"}
    forbidden_new = []
    for hyp, count in hyp_counts.items():
        if count >= 3 and hyp not in committed_hyps:
            accs = hyp_accuracies[hyp]
            forbidden_new.append((hyp, count, max(accs)))

    if not forbidden_new:
        return

    program = read_file(PROGRAM_FILE)
    marker = "## AUTO-DISTILLED FORBIDDEN CHANGES"

    # Build the block
    lines = [f"\n---\n\n{marker}", "> Auto-generated by Distiller. Do NOT attempt these again.\n"]
    for hyp, count, best_acc in sorted(forbidden_new, key=lambda x: -x[1]):
        lines.append(f"- ❌ FORBIDDEN ({count}x tried, best={best_acc:.4f}): {hyp}")
    block = "\n".join(lines) + "\n"

    if marker in program:
        # Replace existing block
        start = program.index(marker) - 5  # include the --- separator
        end = len(program)
        # Find next section after marker
        next_section = program.find("\n## ", program.index(marker) + 10)
        if next_section > 0:
            end = next_section
        new_program = program[:start] + block + program[end:]
    else:
        new_program = program + block

    write_file(PROGRAM_FILE, new_program)
    print(f"  🧠 Distiller: {len(forbidden_new)} forbidden pattern(s) written to program.md")


# ── Plateau detection (ignores audit/syntax failures) ─────────────────────────

def check_plateau(results: list[dict]) -> bool:
    ran = [r for r in results
           if r.get("status") in ("COMMITTED", "REVERTED", "BASELINE")]
    if len(ran) < PLATEAU_WINDOW:
        return False
    recent = [float(r["accuracy"]) for r in ran[-PLATEAU_WINDOW:]]
    return (max(recent) - min(recent)) < PLATEAU_THRESHOLD


# ── Results summariser ─────────────────────────────────────────────────────────

def summarize_results(results: list[dict]) -> str:
    if not results:
        return "No experiments yet. This is the first iteration."

    committed = [r for r in results if r["status"] == "COMMITTED"]
    reverted  = [r for r in results if r["status"] == "REVERTED"]
    failures  = [r for r in results
                 if r["status"] in ("AUDIT_FAILED", "SYNTAX_ERROR", "CODE_FAILED")]

    best = max(results, key=lambda r: float(r["accuracy"]))

    ran = [r for r in results if r["status"] in ("COMMITTED", "REVERTED", "BASELINE")]
    recent_ran = ran[-5:] if ran else []

    plateau_warning = ""
    if len(recent_ran) >= PLATEAU_WINDOW:
        span = max(float(r["accuracy"]) for r in recent_ran) - \
               min(float(r["accuracy"]) for r in recent_ran)
        if span < PLATEAU_THRESHOLD * 2:
            plateau_warning = (
                f"\n⚠️ NEAR-PLATEAU: Recent runs span only {span:.4f}. "
                "Consider more aggressive changes."
            )

    # Collect failed hypothesis texts for Lead Researcher to avoid repeating
    failed_hypotheses = [r["hypothesis"] for r in failures[-10:]]

    lines = [
        f"## Experiment History ({len(results)} total | {len(committed)} committed | "
        f"{len(reverted)} reverted | {len(failures)} code-failed)",
        f"- Best accuracy : {best['accuracy']} — Iter {best['iteration']}: {best['hypothesis']}",
        "",
        "## Last 5 actual training runs:",
    ]
    for r in recent_ran:
        lines.append(
            f"  [{r['status']:9s}] Iter {r['iteration']:3s}: "
            f"acc={float(r['accuracy']):.4f}  — {r['hypothesis'][:60]}"
        )

    if failed_hypotheses:
        lines.append(
            "\n## Code-failed hypotheses (Code Agent couldn't implement these correctly):"
        )
        for h in failed_hypotheses:
            lines.append(f"  - {h[:70]}")

    # Build FORBIDDEN list from repeated-failure hypotheses (3+ reverts, never committed)
    from collections import Counter
    hyp_counts: Counter = Counter()
    for r in ran:
        hyp_counts[r["hypothesis"][:50].strip()] += 1
    committed_hyps = {r["hypothesis"][:50].strip() for r in committed}
    forbidden = [(h, c) for h, c in hyp_counts.items()
                 if c >= 3 and h not in committed_hyps]
    if forbidden:
        lines.append(
            "\n## ⛔ FORBIDDEN — tried 3+ times and never improved accuracy (DO NOT RETRY):"
        )
        for h, c in sorted(forbidden, key=lambda x: -x[1]):
            lines.append(f"  - [{c}x REVERTED] {h[:70]}")
        lines.append(
            "\n⚡ PIVOT REQUIRED: All single-param capacity changes exhausted. "
            "Try: N_LAYERS=1 (throughput), cosine LR schedule, label smoothing, "
            "AdamW betas=(0.9,0.95), WARMUP_STEPS=100, BATCH_SIZE=16."
        )

    lines.append(plateau_warning)
    return "\n".join(lines).strip()


# ── Syntax check (2-second gate before Auditor) ───────────────────────────────

def quick_syntax_check(code: str) -> tuple[bool, str]:
    try:
        ast.parse(code)
        return True, ""
    except SyntaxError as e:
        return False, f"SyntaxError at line {e.lineno}: {e.msg}"


# ── Agent: Lead Researcher ─────────────────────────────────────────────────────

def lead_researcher(
    iteration: int,
    program_goal: str,
    results_summary: str,
    current_train_py: str,
    code_failure_context: str = "",
) -> dict:
    """
    ReCAP-aware planner. Proposes ONE hypothesis.
    code_failure_context: optional feedback from previous audit failures so
    the Lead Researcher can account for implementation difficulty.
    """
    failure_section = ""
    if code_failure_context:
        failure_section = f"""
## ⚠️ PREVIOUS CODE FAILURE (learn from this)
The Code Agent failed to implement the previous hypothesis correctly:
{code_failure_context}
Keep this in mind — prefer changes that are simple to implement surgically
(e.g., single-value changes like a learning rate or dropout value).
""".strip()

    prompt = f"""
# ReCAP — PRIMARY RESEARCH GOAL (re-injected every iteration to prevent plan drift)
{program_goal}

---
# Your Role: Lead Researcher (Iteration {iteration})
Analyse the experiment history and propose exactly ONE specific, testable
hypothesis to improve SST-2 validation accuracy.

## Experiment History
{results_summary}

{failure_section}

## Current train.py
```python
{current_train_py}
```

## Instructions
1. Do NOT repeat any hypothesis that has already been attempted.
2. Propose ONE measurable change with exact values.
3. Prefer SIMPLE changes that are easy to implement surgically
   (e.g., changing a single constant like LEARNING_RATE, DROPOUT, N_LAYERS).
4. Never suggest modifying prepare.py or the evaluate() function.

## Output — return ONLY valid JSON:
{{
  "hypothesis": "<one sentence: what exactly changes>",
  "rationale": "<why this should help, citing results history>",
  "old_snippet": "<exact verbatim snippet from train.py to replace>",
  "new_snippet": "<the replacement — must be valid Python>",
  "risk_level": "low | medium | high",
  "expected_delta": "<e.g. +1.0%>"
}}

IMPORTANT: Include old_snippet and new_snippet directly in your response.
The Code Agent will use these exactly. Make sure old_snippet is copied
verbatim from train.py above.
""".strip()

    response = client.messages.create(
        model=MODEL,
        max_tokens=4096,
        thinking={"type": "adaptive"},
        messages=[{"role": "user", "content": prompt}],
    )

    raw = ""
    for block in response.content:
        if block.type == "text":
            raw = block.text.strip()
            break

    json_match = re.search(r"\{.*\}", raw, re.DOTALL)
    if not json_match:
        return {"hypothesis": "JSON parse failed", "rationale": raw[:200],
                "old_snippet": "", "new_snippet": "", "risk_level": "high",
                "expected_delta": "0"}
    try:
        return json.loads(json_match.group())
    except json.JSONDecodeError:
        return {"hypothesis": "JSON decode failed", "rationale": raw[:200],
                "old_snippet": "", "new_snippet": "", "risk_level": "high",
                "expected_delta": "0"}


# ── Agent: Code Agent (surgical edit mode) ────────────────────────────────────

def code_agent(
    hypothesis: dict,
    current_train_py: str,
    program_goal: str,
    rejection_feedback: str = "",
) -> str:
    """
    Surgical-edit Code Agent.
    If the Lead Researcher already provided old/new snippets in the hypothesis,
    try those first. Otherwise ask the Code Agent to find them.
    If rejection_feedback is provided, the Code Agent must fix the specific issue.
    Returns the modified train.py string (or original if edit fails).
    """
    # ── Fast path: Lead Researcher already supplied the snippets ──────────────
    if not rejection_feedback:
        old_snip = hypothesis.get("old_snippet", "").strip()
        new_snip = hypothesis.get("new_snippet", "").strip()
        if old_snip and old_snip in current_train_py:
            modified = current_train_py.replace(old_snip, new_snip, 1)
            print(f"  ✏️  Fast-path edit: {len(old_snip)}→{len(new_snip)} chars")
            return modified

    # ── LLM path: Code Agent finds the snippet ────────────────────────────────
    rejection_section = ""
    if rejection_feedback:
        rejection_section = f"""
## ⚠️ PREVIOUS ATTEMPT REJECTED — you MUST fix this specific issue:
{rejection_feedback}

Do NOT repeat this mistake. Your new old_snippet/new_snippet must resolve it.
""".strip()

    prompt = f"""
# ReCAP — PRIMARY RESEARCH GOAL (re-injected to prevent plan drift)
{program_goal}

---
# Your Role: Code Agent — Surgical Edit
Implement ONE targeted code change using a find-and-replace approach.
Output ONLY the exact snippet to remove and its exact replacement.

## Hypothesis to Implement
Hypothesis : {hypothesis.get('hypothesis', '')}
Change     : {hypothesis.get('old_snippet', '')} → {hypothesis.get('new_snippet', '')}

## Current train.py
```python
{current_train_py}
```

{rejection_section}

## Output — use EXACTLY these markers (no JSON, no markdown, nothing else):
<<<OLD>>>
<exact verbatim lines from train.py to replace — copy character-for-character including indentation>
<<<NEW>>>
<replacement lines with correct Python indentation>
<<<END>>>

## Rules
1. Lines between <<<OLD>>> and <<<NEW>>> MUST be copied VERBATIM from train.py (str.replace will be used).
2. Lines between <<<NEW>>> and <<<END>>> must be valid Python at the same indentation level.
3. Do NOT change MAX_TRAIN_TIME = 300.
4. Do NOT touch the final two print lines (val_accuracy / peak_memory_mb).
5. Make only the single change the hypothesis describes.
""".strip()

    response = client.messages.create(
        model=MODEL,
        max_tokens=2048,
        messages=[{"role": "user", "content": prompt}],
    )

    raw = ""
    for block in response.content:
        if block.type == "text":
            raw = block.text.strip()
            break

    # ── Marker-based parsing (immune to JSON escaping issues with code) ─────────
    old_match = re.search(r'<<<OLD>>>\n?(.*?)<<<NEW>>>', raw, re.DOTALL)
    new_match = re.search(r'<<<NEW>>>\n?(.*?)<<<END>>>', raw, re.DOTALL)

    if old_match and new_match:
        old_snip = old_match.group(1)
        new_snip = new_match.group(1)
        # Strip only trailing newline added by the marker format
        if old_snip.endswith("\n"):
            old_snip = old_snip[:-1]
        if new_snip.endswith("\n"):
            new_snip = new_snip[:-1]
    else:
        # Fallback: try JSON (handles old cached responses)
        json_match = re.search(r"\{.*\}", raw, re.DOTALL)
        if not json_match:
            print("  ⚠️  Code Agent returned no parseable output")
            return current_train_py
        try:
            edit = json.loads(json_match.group())
        except json.JSONDecodeError:
            print("  ⚠️  Code Agent output unparseable (neither markers nor JSON)")
            return current_train_py
        old_snip = edit.get("old_snippet", "").strip()
        new_snip = edit.get("new_snippet", "").strip()

    if not old_snip:
        print("  ⚠️  Code Agent returned empty old_snippet")
        return current_train_py

    if old_snip not in current_train_py:
        print(f"  ⚠️  old_snippet not found verbatim in train.py")
        print(f"      snippet: {repr(old_snip[:80])}")
        return current_train_py

    modified = current_train_py.replace(old_snip, new_snip, 1)
    print(f"  ✏️  Applied edit: {len(old_snip)}→{len(new_snip)} chars")
    return modified


# ── Full ACT phase: Code Agent → Syntax → Audit (with retry loop) ─────────────

def act_with_self_correction(
    hypothesis: dict,
    current_train_py: str,
    program_goal: str,
    prepare_content: str,
) -> tuple[str, bool, str]:
    """
    Runs the Code Agent → syntax check → Audit loop with up to MAX_CODE_RETRIES.
    On each rejection, the full reason is fed back to the Code Agent for retry.
    Returns (modified_train_py, approved: bool, final_reason: str).
    """
    rejection_feedback = ""

    for attempt in range(1, MAX_CODE_RETRIES + 1):
        print(f"  [Code Agent] Attempt {attempt}/{MAX_CODE_RETRIES}")

        modified = code_agent(hypothesis, current_train_py, program_goal,
                              rejection_feedback)

        if modified == current_train_py and not rejection_feedback:
            # code_agent returned unchanged (snippet not found)
            return current_train_py, False, "old_snippet not found in train.py"

        # ── 2-second syntax gate ──────────────────────────────────────────────
        syntax_ok, syntax_err = quick_syntax_check(modified)
        if not syntax_ok:
            rejection_feedback = (
                f"SYNTAX ERROR on attempt {attempt}: {syntax_err}\n"
                "Fix the indentation or syntax in your new_snippet."
            )
            print(f"  ❌  Syntax check FAILED (attempt {attempt}): {syntax_err}")
            continue

        print(f"  ✅  Syntax check passed")

        # ── Auditor ───────────────────────────────────────────────────────────
        approved, audit_reason = audit_code_agent(
            modified, prepare_content, program_goal
        )

        if approved:
            print(f"  ✅  Audit APPROVED (attempt {attempt}): {audit_reason[:80]}")
            return modified, True, audit_reason

        # Feed rejection reason back to Code Agent for next attempt
        rejection_feedback = (
            f"AUDIT REJECTED on attempt {attempt}: {audit_reason}\n"
            "Fix the exact issue described above in your next old_snippet/new_snippet."
        )
        print(f"  ❌  Audit REJECTED (attempt {attempt}): {audit_reason[:100]}")

    return current_train_py, False, f"Exhausted {MAX_CODE_RETRIES} attempts. Last: {rejection_feedback}"


# ── Agent: Auditor ─────────────────────────────────────────────────────────────

def audit_code_agent(
    modified_train_py: str,
    original_prepare_py: str,
    program_goal: str,
) -> tuple[bool, str]:
    prompt = f"""
# ReCAP — PRIMARY RESEARCH GOAL (re-injected to prevent audit drift)
{program_goal}

---
# Your Role: Auditor
Review the modified train.py. APPROVE or REJECT based on these rules:

## Reject if ANY of these fail:
1. Does NOT import or replicate evaluation logic from prepare.py
2. Does NOT shadow or replace the evaluate() function
3. MAX_TRAIN_TIME = 300 is present and unchanged
4. The final two print lines exist EXACTLY as:
     print(f"val_accuracy: {{val:.4f}}")   ← some variable containing accuracy
     print(f"peak_memory_mb: {{mem:.2f}}") ← some variable containing memory
5. No obvious syntax errors (the file should parse correctly)
6. Training loop still checks the wall-clock time limit

## modified train.py to audit:
```python
{modified_train_py}
```

Return ONLY valid JSON:
{{
  "approved": true,
  "reason": "brief explanation",
  "issues": []
}}
""".strip()

    response = client.messages.create(
        model=MODEL,
        max_tokens=512,
        messages=[{"role": "user", "content": prompt}],
    )

    for block in response.content:
        if block.type == "text":
            raw = block.text.strip()
            json_match = re.search(r"\{.*\}", raw, re.DOTALL)
            if json_match:
                try:
                    data = json.loads(json_match.group())
                    return bool(data.get("approved", False)), data.get("reason", "")
                except json.JSONDecodeError:
                    pass

    return True, "Audit parse failed — cautiously approved"


# ── Training runner ────────────────────────────────────────────────────────────

def run_training(cwd: str = ".") -> tuple[float, float, str]:
    print("  [Runner] uv run train.py  (300s limit)...")
    t0 = time.time()

    try:
        proc = subprocess.run(
            ["uv", "run", "train.py"],
            capture_output=True, text=True,
            timeout=MAX_TRAIN_TIMEOUT_S, cwd=cwd,
        )
        output = proc.stdout + "\n" + proc.stderr
        elapsed = time.time() - t0
        print(f"  [Runner] Finished in {elapsed:.1f}s (exit={proc.returncode})")

    except subprocess.TimeoutExpired:
        print(f"  [Runner] ⚠️  OS timeout after {MAX_TRAIN_TIMEOUT_S}s")
        return 0.0, 0.0, "OS_TIMEOUT"
    except FileNotFoundError:
        print("  [Runner] ⚠️  `uv` not found")
        sys.exit(1)

    acc_m = re.search(r"val_accuracy:\s*([\d.]+)", output)
    mem_m = re.search(r"peak_memory_mb:\s*([\d.]+)", output)
    val_accuracy = float(acc_m.group(1)) if acc_m else 0.0
    peak_memory  = float(mem_m.group(1)) if mem_m else 0.0

    if proc.returncode != 0 and val_accuracy == 0.0:
        print("  [Runner] Training error. Last 15 lines:")
        for line in output.strip().splitlines()[-15:]:
            print(f"    {line}")

    return val_accuracy, peak_memory, output[-800:]


# ── Git helpers ────────────────────────────────────────────────────────────────

def git_commit(iteration: int, hypothesis: str, accuracy: float) -> str:
    msg = f"Exp {iteration}: {hypothesis[:55]} | acc={accuracy:.4f}"
    subprocess.run(["git", "add", TRAIN_FILE, RESULTS_FILE],
                   check=True, capture_output=True)
    r = subprocess.run(["git", "commit", "-m", msg],
                       capture_output=True, text=True)
    if r.returncode != 0:
        print(f"  [Git] Commit failed: {r.stderr.strip()}")
        return "commit_failed"
    h = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                       capture_output=True, text=True)
    return h.stdout.strip()


def git_revert() -> None:
    subprocess.run(["git", "checkout", "HEAD", "--", TRAIN_FILE],
                   check=True, capture_output=True)


def git_log_results() -> None:
    subprocess.run(["git", "add", RESULTS_FILE], capture_output=True)
    subprocess.run(["git", "commit", "--allow-empty",
                    "-m", "chore: update results.tsv"],
                   capture_output=True)


def regenerate_plot() -> None:
    subprocess.run(["uv", "run", "plot_progress.py"], capture_output=True)


# ── Main orchestration loop ────────────────────────────────────────────────────

def main():
    print("=" * 68)
    print("🔬  AutoResearch — Karpathy Loop  |  SST-2 Accuracy Optimiser")
    print("=" * 68)

    for f in [PROGRAM_FILE, TRAIN_FILE, PREPARE_FILE]:
        if not Path(f).exists():
            print(f"❌  Missing: {f}  — run `uv run prepare.py` first.")
            sys.exit(1)

    if not Path("data").exists():
        print("❌  data/ missing — run `uv run prepare.py` first.")
        sys.exit(1)

    cwd = str(Path(__file__).parent.resolve())

    # ── Baseline (skip if already recorded) ───────────────────────────────────
    existing = read_results()
    existing_baseline = next(
        (r for r in existing if r.get("status") == "BASELINE"), None
    )

    if existing_baseline:
        # Use max of all committed/baseline accuracies as the true best
        all_acc = [float(r["accuracy"]) for r in existing
                   if r.get("status") in ("BASELINE", "COMMITTED") and r.get("accuracy")]
        best_accuracy = max(all_acc) if all_acc else float(existing_baseline["accuracy"])
        print(f"\n📊  Resuming — best acc={best_accuracy:.4f}  (skipping baseline re-run)")
    else:
        print("\n📊  Running baseline train.py...")
        baseline_acc, baseline_mem, _ = run_training(cwd)
        print(f"    Baseline → acc={baseline_acc:.4f}  mem={baseline_mem:.1f}MB")
        if baseline_acc == 0.0:
            print("❌  Baseline failed. Fix train.py / prepare.py first.")
            sys.exit(1)
        best_accuracy = baseline_acc
        append_result(0, "Baseline", baseline_acc, "BASELINE", "",
                      baseline_mem, "Initial run")
        subprocess.run(["git", "add", "-A"], capture_output=True)
        subprocess.run(["git", "commit", "--allow-empty",
                        "-m", f"baseline: acc={baseline_acc:.4f}"],
                       capture_output=True)
        print(f"    ✅  Committed baseline={best_accuracy:.4f}\n")

    iteration = max(
        (int(r.get("iteration", 0)) for r in existing if r.get("iteration", "").isdigit()),
        default=0,
    )
    code_failure_context = ""   # persists across iterations for Lead Researcher

    # ── PRAR Research Loop ────────────────────────────────────────────────────
    print("🔁  Starting PRAR Research Loop  (Ctrl-C to stop)\n")
    session_start = datetime.now().strftime("%Y-%m-%d %H:%M")

    while True:
        iteration += 1
        bar = "─" * 68
        print(f"\n{bar}")
        print(
            f"  Iteration {iteration}  |  Best: {best_accuracy:.4f}"
            f"  |  Session: {session_start}"
        )
        print(bar)

        # ── PERCEIVE (ReCAP: re-read program.md) ──────────────────────────────
        program_goal     = read_file(PROGRAM_FILE)
        results          = read_results()
        results_summary  = summarize_results(results)
        current_train_py = read_file(TRAIN_FILE)
        prepare_content  = read_file(PREPARE_FILE)
        print(f"\n[PERCEIVE]  history={len(results)} experiments")

        if check_plateau(results):
            print(
                f"\n🏁  PLATEAU — accuracy hasn't improved >{PLATEAU_THRESHOLD*100:.1f}% "
                f"over last {PLATEAU_WINDOW} training runs."
            )
            print(f"    Best: {best_accuracy:.4f}")
            break

        # ── REASON (Lead Researcher) ──────────────────────────────────────────
        print("\n[REASON — Lead Researcher]")
        hypothesis = lead_researcher(
            iteration, program_goal, results_summary,
            current_train_py, code_failure_context
        )
        print(f"  💡 {hypothesis.get('hypothesis', '?')}")
        print(f"  🔧 {hypothesis.get('old_snippet', '?')[:60]} → "
              f"{hypothesis.get('new_snippet', '?')[:60]}")
        print(f"  📐 risk={hypothesis.get('risk_level','?')}  "
              f"Δ≈{hypothesis.get('expected_delta','?')}")

        # ── ACT (Code Agent + self-correcting audit loop) ─────────────────────
        print("\n[ACT — Code Agent + Audit loop]")
        modified_train_py, approved, final_reason = act_with_self_correction(
            hypothesis, current_train_py, program_goal, prepare_content
        )

        if not approved:
            print(f"  ❌  All {MAX_CODE_RETRIES} attempts failed: {final_reason[:120]}")
            code_failure_context = (
                f"Hypothesis '{hypothesis.get('hypothesis', '?')}' failed after "
                f"{MAX_CODE_RETRIES} attempts. Reason: {final_reason[:200]}"
            )
            append_result(
                iteration, hypothesis.get("hypothesis", "?"), 0.0,
                "CODE_FAILED", "", 0.0, final_reason[:100]
            )
            git_log_results()
            continue

        # Clear failure context on successful edit
        code_failure_context = ""
        write_file(TRAIN_FILE, modified_train_py)

        # ── EXECUTE ───────────────────────────────────────────────────────────
        print("\n[EXECUTE]")
        val_accuracy, peak_memory, _ = run_training(cwd)
        print(f"  val_accuracy : {val_accuracy:.4f}  (best={best_accuracy:.4f})")
        print(f"  peak_memory  : {peak_memory:.1f} MB")

        # ── REFLECT (Ratchet) ─────────────────────────────────────────────────
        print("\n[REFLECT]")
        if val_accuracy > best_accuracy:
            delta = val_accuracy - best_accuracy
            print(f"  🎉  IMPROVEMENT +{delta:.4f} — committing (ratchet locked)")
            commit_hash = git_commit(
                iteration, hypothesis.get("hypothesis", "?"), val_accuracy
            )
            best_accuracy = val_accuracy
            append_result(
                iteration,
                hypothesis.get("hypothesis", "?"),
                val_accuracy, "COMMITTED", commit_hash, peak_memory,
                f"Δ=+{delta:.4f} | {hypothesis.get('old_snippet','')[:40]}→"
                f"{hypothesis.get('new_snippet','')[:40]}",
            )
            print(f"  ✅  {commit_hash}  new best={best_accuracy:.4f}")
        else:
            delta = val_accuracy - best_accuracy
            print(f"  ⬇️   No gain ({delta:+.4f}) — reverting via git reset")
            git_revert()
            append_result(
                iteration,
                hypothesis.get("hypothesis", "?"),
                val_accuracy, "REVERTED", "", peak_memory,
                f"Δ={delta:.4f}",
            )
            print("  ↩️   Reverted to last best train.py")

        git_log_results()
        regenerate_plot()
        distill_beliefs(read_results())

    # ── Final summary ─────────────────────────────────────────────────────────
    regenerate_plot()
    print("\n" + "=" * 68)
    print("📋  AUTORESEARCH COMPLETE")
    print("=" * 68)
    results = read_results()
    committed = [r for r in results if r["status"] == "COMMITTED"]
    print(f"  Experiments run  : {len([r for r in results if r['status'] in ('COMMITTED','REVERTED')])}")
    print(f"  Successful commits: {len(committed)}")
    print(f"  Best accuracy     : {best_accuracy:.4f}")
    if committed:
        print("\n  Top improvements:")
        top = sorted(committed, key=lambda r: float(r["accuracy"]), reverse=True)[:5]
        for r in top:
            print(f"    [{r['commit_hash']}] {r['accuracy']} — {r['hypothesis']}")
    print("\n  See results.tsv and progress.png for the full log.")
    print("=" * 68)


if __name__ == "__main__":
    main()
